os: linux

language: java
services:
  - docker
cache: bundler
dist: focal

install: skip

jobs:
  include:
    - name: failing
      script: true

after_sucess:
  - echo done
  - echo $TRAVIS_TEST_RESULT
after_failure:
  - echo failed
  - echo $TRAVIS_TEST_RESULT

deploy:
  strategy: git
  provider: pages
  cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
